@startuml
title "C4. Контекст"

!include <C4/C4_Container>

Person(student, "Студент", "Пользователь сайта, который изучает лекции и проходит тесты.")
Person(lector, "Преподаватель", "Загружает лекции и тесты.")

System(sait, "Статический сайт", "Веб-приложение для изучения лекций по предмету 'Архитектура информационных систем и сетей'. Поддерживает просмотр лекций и интерактивных схем.")
System(test, "Тесты", "Приложение для проверки знаний по предмету 'Архитектура информационных систем и сетей'.")

Rel(student, sait, "Использует для изучения лекций и просмотра интерактивных схем.")
Rel(lector, sait, "Добавляет и обновляет лекции")
Rel(lector, test, "Добавляет и обновляет тесты.")
Rel(student, test, "Использует для проверки знаний по лекциям.")

@enduml