@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(developer, "Разработчик", "Отвечает за разработку и поддержку приложения")
Person(customer, "Заказчик", "Получает приложение в виде исходного кода и exe-файла")

System(app, "Приложение для тестирования", "Десктопное приложение для проведения тестирования", "Приложение, поставляемое заказчику")
System(web, "Веб-страница", "Десктопное приложение для проведения тестирования", "Приложение, поставляемое заказчику")

Rel(developer, app, "Разрабатывает, собирает и предоставляет приложение", "Разработка")
Rel(customer, app, "Получает код и exe файл (единожды)", "Единоразовая поставка продукта")

Rel(developer, web, "Разрабатывает, собирает и предоставляет приложение", "Разработка")
Rel(customer, web, "Получает код и страницу (единожды)", "Единоразовая поставка продукта")
@enduml